spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true

